# Generated by Django 5.0.7 on 2024-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sales_limca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(to='product.sales_limca'),
        ),
    ]
