# Generated by Django 5.0.7 on 2024-08-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_invoice_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(related_name='products', to='product.sales_limca'),
        ),
    ]
