# Generated by Django 5.0.7 on 2024-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_invoice_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selled_products',
            new_name='Basket',
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
