# Generated by Django 5.0.7 on 2024-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_selled_products_basket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
