# Generated by Django 5.0.7 on 2024-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_invoice_discounted_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='customer', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
