# Generated by Django 5.0.7 on 2024-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
