# Generated by Django 5.0.7 on 2024-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_invoice_returned_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Searching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
