# Generated by Django 5.0.7 on 2024-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_sales_searching'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_limca',
            name='discount_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
