# Generated by Django 5.0.7 on 2024-08-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_sales_limca_discount_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='actual_price',
            new_name='large_price',
        ),
    ]
