# Generated by Django 5.0.7 on 2024-08-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_actual_price_product_large_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales_Searching',
        ),
    ]
