# Generated by Django 5.0.7 on 2024-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_man_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
